### ISSUE TITLE
error pops up saying the plugin could not be started when trying to turn it on in betterdicord plugins settings

### ISSUE THREAD

**Issue by jack652** [iyu46/RemovedConnectionAlerts#19] opened 2023-12-03 16:56 UTC
<img width="255" alt="image" src="https://github.com/iyu46/RemovedConnectionAlerts/assets/48365199/ea8d7b77-7332-4f32-989a-0e7f7e5751fb">

windows 11
discord Stable 250833 (84e28a2)

**Comment by no1dead** [comment] 2024-02-07 10:21
Stopped working on. Stable 264272 (5d73bfa) Win11

**Comment by dragonunitedtm** [comment] 2024-03-25 02:04
ditto on stable 277953 ( 2ff410b)

**Comment by iyu46** [comment] 2024-04-02 08:37
dupe of #6. In the newest version 0.8.0, I added an error screen that will catch this issue and inform the user of future steps. Going forward in the future, please make regular backups of your history file in the case that this happens again. I'll be working on more measures against this problem since it's quite a difficult one to figure out the root cause for.

**Closed by iyu46** 2024-04-02 08:37 UTC
